import type { Metadata } from "next";
import localFont from 'next/font/local'
import "./globals.css";


const vazirMatn = localFont({
  src: './fonts/webfonts/Vazirmatn[wght].woff2',
  weight: '100 900',
  variable: '--font-sans',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body
        className={`${vazirMatn.className} antialiased h-full flex overflow-hidden`}
      >
        <main className=" w-full h-screen flex flex-col overflow-y-auto">
          {children}
        </main>
      </body>
    </html>
  );
}
