import type { Metadata } from "next";
import localFont from 'next/font/local'
import { TooltipProvider } from '@/components/ui/tooltip';
import { Toaster } from "@/components/ui/sonner";
import LenisScroll from '@/components/lenis-scroll';
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";


const vazirMatn = localFont({
  src: './fonts/webfonts/Vazirmatn[wght].woff2',
  weight: '100 900',
  variable: '--font-sans',
})

export const metadata: Metadata = {
  title: "Next RTL Demo App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa-IR" dir="rtl" className="light">
      <body className={`${vazirMatn.className} antialiased h-full`}>
        <ThemeProvider>          
          <TooltipProvider>
            <LenisScroll />
            {children}
            <Toaster />
          </TooltipProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}




