import type { Metadata } from "next";
import localFont from 'next/font/local'
import Header from "@/components/header";
import { cn } from "@/lib/utils";
import "./globals.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


const vazirMatn = localFont({
  src: '../fonts/webfonts/Vazirmatn[wght].woff2',
  weight: '100 900',
  variable: '--font-sans',
})

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="fa-IR"
      dir="rtl"
      className={cn("h-full", "antialiased", vazirMatn.className)}
    >
      <body className="min-h-screen flex flex-col">
        <div className="overflow-y-auto">
          <Header />
          <main className="min-w-sm h-[calc(100vh-4rem)] flex flex-col items-center bg-zinc-50 font-sans dark:bg-black">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
